
apiVersion: v1
kind: Service
metadata:
  name: timeserv
  labels:
    app: timeserv
spec:
  selector:
    app: timeserv
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 8080
    protocol: TCP
    name: timeserv
