apiVersion: v1
kind: Service
metadata:
  name: timeservs
  labels:
    app: timeservs
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: timeserv
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: timeservr
  labels:
    app: timesevr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: timeservr
    spec:
      containers:
      - name: timeservc
        image: eastcoresolis/timeserv:latest
        ports:
        - containerPort: 8080
