apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfinterview
  labels:
    app: tfinterview
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tfinterview
  template:
    metadata:
      labels:
        app: tfinterview
    spec:
      containers:
      - name: tfinterview
        image: eastcoreesolis/core:tfinterview
        ports:
        - containerPort: 8080
