apiVersion: v1
kind: Service
metadata:
  name: tfinterview
  labels:
    app: tfinterview
spec:
  selector:
    app: tfinterview
  type: NodePort
  ports:
  - port: 80
    nodePort: 30081
    targetPort: 8081
    protocol: TCP
    name: tfinterview
